### ISSUE TITLE
grpc + tensorflow + swift

### ISSUE THREAD

**Issue by johndpope** [acerbetti/TensorFlowPod#1]
Ciao Stefano, @acerbetti,

We're working on this ticket to get tensorflow working on swift server side (not ios).
https://github.com/tensorflow/tensorflow/issues/19 

It looks like you have made some progress on ios side.
Did you have any experience using  swift package manager?
If you have any spare time - would appreciate your input.

JP

**Comment by johndpope** [comment]
https://github.com/nubbel/swift-tensorflow

Updates

**Comment by acerbetti** [comment]
Sorry John, this project was an experiment and I got busy with other things...

good to see you made some progress
